files += Dir.glob(File.join(app.project_dir, 'vendor/arel/lib/**/*.rb'))

file_dependencies 'arel/attributes/attribute' => 'arel/attributes'

file_dependencies 'arel/visitors/visitor' => 'arel/attributes'
file_dependencies 'arel/visitors/depth_first' => 'arel/attributes'
file_dependencies 'arel/visitors/to_sql' => 'arel/attributes'
file_dependencies 'arel/visitors/sqlite' => 'arel/attributes'
file_dependencies 'arel/visitors/postgresql' => 'arel/attributes'
file_dependencies 'arel/visitors/mysql' => 'arel/attributes'
file_dependencies 'arel/visitors/mssql' => 'arel/attributes'
file_dependencies 'arel/visitors/oracle' => 'arel/attributes'
file_dependencies 'arel/visitors/join_sql' => 'arel/attributes'
file_dependencies 'arel/visitors/where_sql' => 'arel/attributes'
file_dependencies 'arel/visitors/order_clauses' => 'arel/attributes'
file_dependencies 'arel/visitors/dot' => 'arel/attributes'
file_dependencies 'arel/visitors/ibm_db' => 'arel/attributes'
file_dependencies 'arel/visitors/informix' => 'arel/attributes'

file_dependencies 'arel/nodes/node' => 'arel/nodes'
file_dependencies 'arel/nodes/select_statement' => 'arel/nodes'
file_dependencies 'arel/nodes/select_core' => 'arel/nodes'
file_dependencies 'arel/nodes/insert_statement' => 'arel/nodes'
file_dependencies 'arel/nodes/update_statement' => 'arel/nodes'
file_dependencies 'arel/nodes/terminal' => 'arel/nodes'
file_dependencies 'arel/nodes/true' => 'arel/nodes'
file_dependencies 'arel/nodes/false' => 'arel/nodes'
file_dependencies 'arel/nodes/unary' => 'arel/nodes'
file_dependencies 'arel/nodes/ascending' => 'arel/nodes'
file_dependencies 'arel/nodes/descending' => 'arel/nodes'
file_dependencies 'arel/nodes/unqualified_column' => 'arel/nodes'
file_dependencies 'arel/nodes/with' => 'arel/nodes'
file_dependencies 'arel/nodes/binary' => 'arel/nodes'
file_dependencies 'arel/nodes/equality' => 'arel/nodes'
file_dependencies 'arel/nodes/in' => 'arel/nodes'
file_dependencies 'arel/nodes/join_source' => 'arel/nodes'
file_dependencies 'arel/nodes/delete_statement' => 'arel/nodes'
file_dependencies 'arel/nodes/table_alias' => 'arel/nodes'
file_dependencies 'arel/nodes/infix_operation' => 'arel/nodes'
file_dependencies 'arel/nodes/over' => 'arel/nodes'

file_dependencies 'arel/nodes/and' => 'arel/nodes'
file_dependencies 'arel/nodes/function' => 'arel/nodes'
file_dependencies 'arel/nodes/count' => 'arel/nodes'
file_dependencies 'arel/nodes/extract' => 'arel/nodes'
file_dependencies 'arel/nodes/values' => 'arel/nodes'
file_dependencies 'arel/nodes/named_function' => 'arel/nodes'
file_dependencies 'arel/nodes/window' => 'arel/nodes'
file_dependencies 'arel/nodes/inner_join' => 'arel/nodes'
file_dependencies 'arel/nodes/outer_join' => 'arel/nodes'
file_dependencies 'arel/nodes/string_join' => 'arel/nodes'
file_dependencies 'arel/nodes/sql_literal' => 'arel/nodes'

file_dependencies 'arel/nodes' => 'arel'